// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jviadjixdekolzwcqmrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aWFkaml4ZGVrb2x6d2NxbXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDYwMDUsImV4cCI6MjA2ODA4MjAwNX0.hlrOixGxAl_llSqsnQqJuekH2HLubJC1Kq-XE_BTgh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});